### ISSUE TITLE
prerelease_staging out of disk space

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/infrastructure#109]
<pre>
admin@prerelease_staging:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
<strong>/dev/root        20G   19G     0 100% /</strong>
devtmpfs        488M     0  488M   0% /dev
tmpfs           490M  4.0K  490M   1% /dev/shm
tmpfs           490M   51M  440M  11% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           490M     0  490M   0% /sys/fs/cgroup
<pre>

**Comment by DanVanAtta** [comment]
Let's cut this in triple-game to reflect the production impact and give this the proper visibility, this is a release blocker.

**Comment by DanVanAtta** [comment]
To fix, looks like we need to clean up old deployments. There are 203 bot installations and 215 lobby installs. It's interesting the individual size of the lobby install is up to 30MB, regardless, if we never clean up we'll run out of space.

**Comment by ssoloff** [comment]
Closing; migrated to triplea-game/triplea#3828.
