### ISSUE TITLE
Infrastructure - Walk Through and Q&A

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/infrastructure#3]
## Code as Infrastructure - Deployment from Source Control

This project allows us to control infrastructure by making code changes and checking them in after which servers running update loops will see the changes and run update scripts.

The key file is host_control which maps host names to which application should be installed on each: https://github.com/DanVanAtta/infrastructure/blob/master/roles/host_control.sh

The current example sets up a latest prerelease lobby that updates on every merge. That server is also connected to a support server that is running metrics and graphing. Each server is also automatically connected to paper trail (centralized logging):

```
case "$(hostname)" in
  prerelease_staging)
    ${LOBBY_DB} --port=5432 --tag-name=${LATEST_TAG}
    ${LOBBY} --lobby-port 7000 --database-port 5000 --tag-name ${LATEST_TAG}
    ${BOT} --start_port 8000 --count 2 --lobby-port 7000 --tag-name ${LATEST_TAG}
    ;;
  infra-support)
    ${PROMETHEUS}
    ${GRAFANA}
    ;;
  *)
    reportError "Unknown host: $(hostname)"
  ;;
esac
```

We could add a prod node that would automatically update on each latest release, that would look like:

```
case "$(hostname)" in
  production.hostname)
    ${LOBBY} --lobby-port 7000 --database-port 5000 --tag-name ${LATEST_BUILD}
    ;;
  *)
    reportError "Unknown host: $(hostname)"
  ;;
esac
```

Or we could pin a host to a specific version if we'd like (and checking in an updated version value woudl trigger an update on the server):

```
case "$(hostname)" in
  testing.hostname)
    ${LOBBY_DB} --port=5432 --tag-name=1.9.0.0.35251
    ;;
  *)
    reportError "Unknown host: $(hostname)"
  ;;
esac
```

Currently servers are checking for updates every minute, that will likely be dialed back to once every 5.

## Setup of servers
- one time install of a cronjob, README project gives the command that needs to be run, it's the same for any server
- run script to set server hostname and then reboot
- add entry in host_control file and merge

## Features

The updates are broken to two groups, system and 'role'. System updates are applied to every server uniformly, this includes:
- creation of triplea user
- copies authorized user public keys (by checking in your public key you'll get access to all servers)
- sets up firewall and base security packages like `fail2ban`
- sets up a 'node exporter' to send metrics
- papertrail integration; syslog messages sent to papertrail

### Application list
The folowing applications can be set up by configuring roles in host_control:
- prometheus
- grafana
- lobby database (with flyway to run migrations)
- lobby application

To complete the list we still need:
- dice server
- forum (maybe)
- lobby bots

### Always latest pre-release lobby
http://172.104.27.19:7000

Every merge will cause a new lobby to be deployed at this location. There is a DB deployed to the same machine that will pick up the latest checked in flyway migration files.

### Grafana
http://172.104.27.19:3000 (gitter me for for an invite link)

This is a metric visualization tool, this is a way to graph the data sent to prometheus

![grafana](https://user-images.githubusercontent.com/12397753/38170053-1ed1a340-3530-11e8-9892-e1d1fb8ae80c.png)

### Gitter integrated deployment status room
https://gitter.im/triplea-game/testing

Notification channel for latest deployment versions and notifications of any errors.

![deploy_status](https://user-images.githubusercontent.com/12397753/38169971-de9ef108-352d-11e8-9f71-d711543a6111.png)

## Paper Trail

A web UI where we send all logs and can view them and search on them. This is not a free service, or at least the free plan is pretty limited, we may need to spend $5 per month for a higher log limit (if we like this tool):

Logs are also forked to file system and stored in `/root/logs/<year>/<month>/<day>/<hour>/log...` 

![papertrail](https://user-images.githubusercontent.com/12397753/38170082-ce240234-3530-11e8-8121-827ec70e64b3.png)

### Prometheus Metrics Aggregation
http://172.104.27.19:9090/graph

This collects metrics and stores them. We can potentially configure prometheus to send us alerts, for example could get SMS messages if lobby dies.

![prom](https://user-images.githubusercontent.com/12397753/38170091-f9d43cbe-3530-11e8-90ea-90d13d33ae43.png)

## Techncal components

First key file to note is: (system update)[https://github.com/DanVanAtta/infrastructure/blob/master/system_update.sh]

The installed cron job gets a fresh git clone and calls the cron update script. The cron update script sets up the logging folder and calls `system_update.sh`

System_update is effectively the entry point in the system, it calls system and then host control.

### System Control

https://github.com/DanVanAtta/infrastructure/blob/master/root/system_control.sh

Run universally on all machines every update iteration

### Host Control

https://github.com/DanVanAtta/infrastructure/blob/master/roles/host_control.sh

As mentioned above, runs host specific instructions, captures the configuration per host.

```
case "$(hostname)" in
  prerelease_staging)
    ${LOBBY_DB} --port=5432 --tag-name=${LATEST_TAG}
    ${LOBBY} --lobby-port 7000 --database-port 5000 --tag-name ${LATEST_TAG}
    ${BOT} --start_port 8000 --count 2 --lobby-port 7000 --tag-name ${LATEST_TAG}
    ;;
  infra-support)
    ${PROMETHEUS}
    ${GRAFANA}
    ;;
  *)
    reportError "Unknown host: $(hostname)"
  ;;
esac
```

**Comment by DanVanAtta** [comment]
my 2 cents; re-target the sub-domain to the automated lobby. I don't think we need the by-hand one any longer.

There are still some next steps in all this:
- add a role for bot host
- experiment with flyway.conf file for setting a baseline migration
- add some configurations for production to host control
- deploy cronjob to prod bot servers
- deploy cronjob to prod lobby
- cleanup: delete triplea-game/lobby repo
- documentation updates and consolidation to infrastructure
- finalize gitter rooms, decide which room will receive infrastructure notifications (maybe just rename 'testing' room to 'infrastructure')

**Comment by RoiEXLab** [comment]
@DanVanAtta 
I'd be happy to re-route the subdomain to the new automated lobby.
However I'd like to get a 👍 or something from @ssoloff
And some clarification on what server does what.
Currently there are 3 servers:
Staging-Lobby (probably the staging lobby created by @ssoloff)
prerelease_staging (?)
infra-support (??)

So which one should get the staging-lobby subdomain?

**Comment by RoiEXLab** [comment]
`lobby-staging.triplea-game.org` now points to `66.175.213.79` and `2600:3c03::f03c:91ff:fe53:e36e` and the old "Staging-Lobby" server was completely removed.

**Comment by RoiEXLab** [comment]
According to papertrail, bots seem to be constantly crashing due to running out of memory on the pre-release lobby

**Comment by DanVanAtta** [comment]
In absence of any specific questions, will close this thread.
