### ISSUE TITLE
Use pure systemd instead of sysvinit "wrapper"

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/infrastructure#40]
Just a small note:
We currently use the `service triplea-bot@<number> start|stop|restart|status` etc. command to start and stop bots, however this is the "legacy" SysVinit syntax that is kept for backwards compatibility.
We should prefer the systemd syntax `systemctl start|stop|restart|reload|status triplea-bot@<number>` to be more consistent with all the other systemd related commands.
When changing this we should tell all the people having access (like prastle) about this

**Comment by DanVanAtta** [comment]
We create some helper 'start/stop' scripts, an update there would be a good step.

**Comment by DanVanAtta** [comment]
Migrated to: https://github.com/triplea-game/triplea/issues/3942
