### ISSUE TITLE
disable bots when decreasing bot count (automatically disable unit files that should not be started)

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/infrastructure#42]
The `systemctl disable <unit>` command does not support patterns i.e. using `triplea-bot@*`, but this should be achieveable by combining `systemctl list-units triplea-bot@*`, potentially `grep` to avoid re-enabling units (And maybe to filter uneccessary output?) and the normal disable command.

**Comment by RoiEXLab** [comment]
Here's a proposal of a potential snippet, haven't tested if it's actually working because time.
```bash
systemctl reset-failed triplea-bot@*.service # Cleanup crashed, non-existent bots from systemctl list-units

local installedUnits=$(systemctl list-units triplea-bot@*.service --all --no-legend | grep -Po --colour=never "(?<=^triplea-bot@)\d+(?=\.service)")
for botNumber in installedUnits; do
    if (( botNumber > botCount )); then
      systemctl disable triplea-bot@$botNumber --now # Should we enforce shutdown of any "additional bots"?
    fi
done
```
This script should be placed somewhere in the [install_service_files.sh](https://github.com/triplea-game/infrastructure/blob/20080d0b170f0af60b9962a5df370ec4a8dee928/roles/bot/tasks/install_service_files.sh) file

A variation of this script should of course also be placed [below here](https://github.com/triplea-game/infrastructure/blob/20080d0b170f0af60b9962a5df370ec4a8dee928/roles/bot/files/uninstall_bot.sh#L19)

**Comment by DanVanAtta** [comment]
Interesting proposal @RoiEXLab . Do you have any idea how the 5th bot was added? Was it like that on all servers? Do we have somewhere an off-by-one error somewhere in the infrastructure scripts, or was the problem perhaps due to the old install script files being run?

> # Should we enforce shutdown of any "additional bots"?
My 2 cents, answer is yes.

**Comment by DanVanAtta** [comment]
Yeah, they were not properly disabled, my mistake. I renamed this issue to describe the use-case that is not supported and was at fault here. The linodes should have been recycled and new ones used rather than trying to lower the bot-count.
