### ISSUE TITLE
travis-ci.com running without any travis file.

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/infrastructure#57]
Looks like https://github.com/triplea-game/triplea/issues/3427 had the side effect of enabling travis for repositories that are not using it.
Someone with write access should be able to disable it again for those repositories

**Comment by DanVanAtta** [comment]
ya, i saw it was 'on' for infrastructure, turned off but it did not take. It seems there is a 'save' button somewhere that I probably needed to click.

**Comment by DanVanAtta** [comment]
Perhaps this ia moot point, https://travis-ci.org/triplea-game, looks like we're not seeing travis ci builds for infra

![screenshot from 2018-09-01 11-33-45](https://user-images.githubusercontent.com/12397753/44948883-e8805380-adda-11e8-9b45-8611d9cb7ae0.png)
