### ISSUE TITLE
admin user should be able to use journalctl

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/infrastructure#8]
triplea user is a bit handicapped from seeing logs:
```
triplea@localhost:~$ journalctl
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.
```

adding journalctl to sudo permissions would like fix; might be other fixes too..

**Comment by RoiEXLab** [comment]
You can give the triplea user limited sudo access to be able to just execute journalctl with sudo

**Comment by DanVanAtta** [comment]
Can close, pretty sure admin user has journalctl. Easy to open a new issue to track any outstanding items.
